"""Add auto-increment to task id

Revision ID: 63dc0bbc9861
Revises: 0520ffaea164
Create Date: 2024-07-30 19:34:30.123096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63dc0bbc9861'
down_revision: Union[str, None] = '0520ffaea164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
